### ISSUE TITLE
ErrorException in Repository.php line 352:

### ISSUE THREAD

**Issue by yuri25** [marcoax/maguttiCms#4]
ErrorException in Repository.php line 352:
This cache store does not support tagging. (View: C:\OpenServer\domains\magutti\resources\views\admin\home.blade.php)

**Comment by yuri25** [comment]
Solved... 
I'm not sure that everything is correct, but I'll write here:
- Go to .env and write CACHE_DRIVER=array
- Go to C:\OpenServer\domains\magutti\config\cache.php and write  'default' => env('CACHE_DRIVER', 'array'),
- in console: $$  php artisan config:cache

**Comment by marcoax** [comment]
Hi
Yes tour is the correct way
I don't know why in some case  this happens
In my installation i don't have the problem but on a mac I've seen the same
problem



Il 19 feb 2017 12:38 AM, "Yuran" <notifications@github.com> ha scritto:

Solved...
I'm not sure that everything is correct, but I'll write here:

   - Go to .env and write CACHE_DRIVER=array
   - Go to C:\OpenServer\domains\magutti\config\cache.php and write
   'default' => env('CACHE_DRIVER', 'array'),
   - in console: $$ php artisan config:cache

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/marcoax/maguttiCms/issues/4#issuecomment-280883493>,
or mute
the thread
